name: Sync FreshRSS ⭐️ → Raindrop.io

on:
  schedule:
    - cron: '*/60 * * * *'  # ogni 30 minuti
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        run: python main.py
        env:
          FRESHRSS_URL: ${{ secrets.FRESHRSS_URL }}
          FRESHRSS_USER: ${{ secrets.FRESHRSS_USER }}
          FRESHRSS_PASSWORD: ${{ secrets.FRESHRSS_PASSWORD }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}

      - name: Commit & Force Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add synced.json
          git commit -m "update synced.json" || echo "Nothing to commit"
          git push --force
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
