name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Reset branch to origin
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Run script
        run: python main.py
        env:
          FRESHRSS_URL: ${{ secrets.FRESHRSS_URL }}
          FRESHRSS_USER: ${{ secrets.FRESHRSS_USER }}
          FRESHRSS_PASSWORD: ${{ secrets.FRESHRSS_PASSWORD }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}

      - name: Commit and push if changed
        run: |
          git add synced.json
          git diff --cached --quiet || git commit -m "update synced.json"
          git push origin main
